# Generated by scripts/render-formula.sh for v0.1.0. Do not edit by hand.
class Cloudburrow < Formula
  desc "Local Google Cloud emulator for development and testing"
  homepage "https://github.com/cloudburrow/cloudburrow"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/cloudburrow/cloudburrow/releases/download/v0.1.0/cloudburrow_v0.1.0_darwin_arm64.tar.gz"
      sha256 "447afb8f0f5e77ecf2d609dcba835ce0da39bdcbf430aa76eebb0b1accc51c89"
    end
    on_intel do
      url "https://github.com/cloudburrow/cloudburrow/releases/download/v0.1.0/cloudburrow_v0.1.0_darwin_amd64.tar.gz"
      sha256 "41fb4c1d18923fd8620ade5b7598de51da172421a30eaea6806e5b9531c9562b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cloudburrow/cloudburrow/releases/download/v0.1.0/cloudburrow_v0.1.0_linux_arm64.tar.gz"
      sha256 "c4025d92e43c9a102cae16c00e9e1227cab42b66eac969723296aa1a961e9448"
    end
    on_intel do
      url "https://github.com/cloudburrow/cloudburrow/releases/download/v0.1.0/cloudburrow_v0.1.0_linux_amd64.tar.gz"
      sha256 "ed4edffac9112b42777cb250c180a1dcf502bbf4882abef6636c0e60426b04fe"
    end
  end

  def install
    bin.install "cloudburrow"
  end

  test do
    assert_match "cloudburrow v0.1.0", shell_output("#{bin}/cloudburrow version")
  end
end
